<?php

use Drupal\Core\Entity\EntityTypeManager;
use Drupal\node\Entity\Node;
use Drupal\maestro\Entity\MaestroProcess;


/**

Implements hook_maestro_engine_process_completed().
*/
function project_update_fields_maestro_maestro_engine_process_completed(MaestroProcess $process) {

  // Check if the process completed is for the template with ID 'new_project'.

  \Drupal::logger('project_update_fields_maestro')->notice($process->template->id());

  if ($process->template->id() == 'new_project') {

    // Load the project node.
    $project = Node::load($process->getAttachedEntity('project')->id());
    // Load the step_one node.
    $step_one_node = $process->getAttachedEntity('step_one');
    // Load the step_two node.
    $step_two_node = $process->getAttachedEntity('step_two');
    // Get the selected value from project field_type.
    $selected_type = $project->field_type->value;
    // Load the step_three or step_four node based on the selected value.

    \Drupal::logger('project_update_fields_maestro')->notice($step_one_node->id());

    if ($selected_type == 'triennial') {
      $step_three_node = $process->getAttachedEntity('step_three');
      $step_four_node = NULL;
    }
    else {
      $step_four_node = $process->getAttachedEntity('step_four');
      $step_three_node = NULL;
    }

    // Update the project node fields.

    $project->field_module_one = ['target_id' => $step_one_node->id()];
    $project->field_module_two = ['target_id' => $step_two_node->id()];

    if ($step_three_node) {
      $project->field_module_three = ['target_id' => $step_three_node->id()];
    }
    else {
      $project->field_module_three = ['target_id' => $step_four_node->id()];
    }

    // Save the project node.
    $project->save();
  }
}
